---
version: 2
default: &defaults
  working_directory: /home/circleci/x86
  machine:
    image: circleci/classic:edge
workflows:
  version: 2
  checkout_build_help_test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root:  .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make amd64
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-amd64
